printWidth: 200
# tabWidth: 2
# useTabs: false
# semi: true
singleQuote: true
# quoteProps: 'as-needed'
trailingComma: 'none'
bracketSpacing: false
# jsxBracketSameLine: false
# arrowParens: 'always'

overrides:
  - files: '*.yml'
    options:
      parser: yaml
      semi: false
